'use strict';
const DATA=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const OFFLINE=JSON.parse(document.getElementById('offline-osm').textContent);
const T0=Date.UTC(2017,0,1),YEAR=365.25*86400000,OBS=2017+(Date.parse(DATA.summary.solutionDate)-T0)/YEAR;
const state={view:'supplied',station:'RY99',t:OBS,frame:'plate',reference:'csv',event:false,playing:false,story:0,center:[44,24.5],zoom:5,osm:true};
const colors=['#175d59','#216b9c','#946007'],axes=['East','North','Ellipsoidal Up'],reduced=matchMedia('(prefers-reduced-motion: reduce)');
const f=(x,n=2)=>Number.isFinite(x)?(x<0?'−':'+')+Math.abs(x).toFixed(n):'—',mm=x=>Number.isFinite(x)?f(x)+' mm':'—';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function node(tag,attrs={},parent){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(parent)parent.appendChild(e);return e;}
function text(x,y,content,parent,attrs={}){const e=node('text',{x,y,...attrs},parent);e.textContent=content;return e;}
function station(){return DATA.stations.find(s=>s.id===state.station);}
function epochDate(v){if(!v||v==='00:000:00000')return null;const [y,d,sec]=v.split(':').map(Number);return Date.UTC(y>=80?1900+y:2000+y,0,1)+(d-1)*86400000+sec*1000;}
function segment(s,t=state.t){const ms=T0+(t-2017)*YEAR;return s.segments.find(r=>(epochDate(r.start)===null||ms>=epochDate(r.start))&&(epochDate(r.end)===null||ms<epochDate(r.end)))||null;}
function basis(s){const a=s.lat*Math.PI/180,l=s.lon*Math.PI/180;return [[-Math.sin(l),Math.cos(l),0],[-Math.sin(a)*Math.cos(l),-Math.sin(a)*Math.sin(l),Math.cos(a)],[Math.cos(a)*Math.cos(l),Math.cos(a)*Math.sin(l),Math.sin(a)]];}
const mul=(m,v)=>m.map(r=>r.reduce((sum,x,i)=>sum+x*v[i],0)),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]);
const W=[1.199,-.107,1.468].map(v=>v*Math.PI/(180*3600000));
function geographicXYZ(s){const p=s.lat*Math.PI/180,l=s.lon*Math.PI/180,e2=.0066943800229,N=6378137/Math.sqrt(1-e2*Math.sin(p)**2);return [(N+s.height)*Math.cos(p)*Math.cos(l),(N+s.height)*Math.cos(p)*Math.sin(l),(N*(1-e2)+s.height)*Math.sin(p)];}
function rigid(s){const r=segment(s,OBS),xyz=r?r.snxXYZ:geographicXYZ(s);return mul(basis(s),cross(W,xyz)).map(v=>v*1000);}
function result(s=station(),t=state.t){const r=segment(s,t),dt=t-2017;
 if(state.view==='supplied'){
  if(!r||!s.solution)return null;
  const snx=state.reference==='snx',base=snx?r.snxXYZ:r.xyz,velocity=snx?r.snxVelocity:r.velocity;
  const rotated=cross(W,s.solution.xyz).map(v=>-v*dt),aligned=add(s.solution.xyz,rotated),propagated=add(base,velocity.map(v=>v*dt));
  const raw=mul(basis(s),sub(s.solution.xyz,base)).map(v=>v*1000),correction=mul(basis(s),rotated).map(v=>v*1000),trend=mul(basis(s),velocity).map(v=>-v*dt*1000);
  return {values:mul(basis(s),sub(aligned,propagated)).map(v=>v*1000),terms:[raw,correction,trend],labels:['Raw cross-frame coordinate difference','Published frame rotation correction','Reference velocity correction'],r,base,velocity,aligned,propagated};
 }
 const plate=rigid(s).map(v=>state.frame==='global'?v*dt:0),phase=(s.lon-40)*.3,rate=[1.2*Math.sin(phase),.8*Math.cos(phase),-.5],amplitude=[2,1.5,4];
 const local=rate.map(v=>state.view==='illustrative'?v*dt:0),periodic=amplitude.map(v=>state.view==='illustrative'?v*(Math.sin(2*Math.PI*dt+phase)-Math.sin(phase)):0),event=[25,-12,8].map(v=>state.view==='illustrative'&&state.event&&t>=2025?v:0);
 let terms=[plate,local,periodic,event];if(state.frame==='static')terms=terms.map(()=>[0,0,0]);return {values:terms.reduce(add,[0,0,0]),terms,labels:['Published rigid-plate prediction','Synthetic local trend','Synthetic annual change','Synthetic event offset'],r};
}
function formalReferenceSigma(r,t){const dt=t-2017,R=basis(station()),C=r.covariance,P=Array.from({length:3},(_,i)=>Array.from({length:3},(_,j)=>C[i][j]+dt*(C[i][j+3]+C[i+3][j])+dt*dt*C[i+3][j+3]));return R.map(a=>Math.sqrt(Math.max(0,a.reduce((v,x,i)=>v+a.reduce((u,y,j)=>u+x*P[i][j]*y,0),0)))*1000);}
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),5500);}
// Map geography uses Web Mercator so online tiles and local boundaries share one transform.
const world=(lon,lat)=>[(lon+180)/360,(1-Math.asinh(Math.tan(Math.max(-85,Math.min(85,lat))*Math.PI/180))/Math.PI)/2];
function xy(lon,lat){const a=world(lon,lat),c=world(...state.center),size=256*2**state.zoom;return [425+(a[0]-c[0])*size,240+(a[1]-c[1])*size];}
function screenWorld(x,y){const c=world(...state.center),size=256*2**state.zoom;return [c[0]+(x-425)/size,c[1]+(y-240)/size];}
function lonlat(x,y){return [x*360-180,Math.atan(Math.sinh(Math.PI*(1-2*y)))*180/Math.PI];}
function polygonPath(geometry){const polys=geometry.type==='MultiPolygon'?geometry.coordinates:[geometry.coordinates];return polys.map(poly=>poly.map(ring=>ring.map((c,i)=>(i?'L':'M')+xy(...c).map(v=>v.toFixed(2)).join(',')).join('')+'Z').join('')).join('');}
// The background uses embedded OSM vectors, never remote map tiles.
function offlineBackground(){
 const g=$('tiles');g.replaceChildren();if(!state.osm)return;
 const c=world(...state.center),size=256*2**state.zoom,L=c[0]-425/size,R=c[0]+425/size,T=c[1]-240/size,B=c[1]+240/size;
 const roads=node('g',{transform:`translate(${425-c[0]*size} ${240-c[1]*size}) scale(${size})`,'pointer-events':'none'},g);
 for(const kind of ['trunk','motorway']){
  const d=OFFLINE.roads.filter(r=>r.k===kind&&r.b[2]>=L&&r.b[0]<=R&&r.b[3]>=T&&r.b[1]<=B).map(r=>r.d).join('');
  if(d){node('path',{d,fill:'none',stroke:'#fffaf0','stroke-width':3.8,'vector-effect':'non-scaling-stroke'},roads);node('path',{d,fill:'none',stroke:kind==='motorway'?'#c4a677':'#d0bf9c','stroke-width':kind==='motorway'?1.7:1.1,'vector-effect':'non-scaling-stroke'},roads);}
 }
 const occupied=[],marks=DATA.stations.map(s=>xy(s.lon,s.lat)),measure=document.createElement('canvas').getContext('2d');measure.font='13px "Segoe UI",Arial,sans-serif';
 // Label priority and offsets are fixed; collisions suppress a label, not a city.
 for(const place of OFFLINE.cities){
  const [x,y]=xy(place.lon,place.lat);if(x<30||x>805||y<65||y>412)continue;
  node('circle',{cx:x,cy:y,r:2,fill:'#687366'},g);
  const width=measure.measureText(place.name).width,height=16;let box=null;
  for(const [dx,dy]of [[6,-6],[6,19],[-width-6,-6],[-width-6,19]]){
   const q={x:x+dx,y:y+dy-13,w:width,h:height};
   if(q.x<38||q.x+q.w>808||q.y<72||q.y+q.h>412)continue;
   if(occupied.some(a=>q.x<a.x+a.w+7&&q.x+q.w+7>a.x&&q.y<a.y+a.h+5&&q.y+q.h+5>a.y))continue;
   if(marks.some(([sx,sy])=>sx>q.x-6&&sx<q.x+q.w+6&&sy>q.y-6&&sy<q.y+q.h+6))continue;
   box=q;break;
  }
  if(box){occupied.push(box);text(box.x,box.y+13,place.name,g,{fill:'#5c6258',style:'font-size:13px',stroke:'#fbfaf5','stroke-width':3,'paint-order':'stroke','stroke-linejoin':'round'});}
 }
 $('mapStatus').textContent=state.zoom>8?'OSM offline · regional detail only':'OpenStreetMap · offline regional map';
 $('attribution').innerHTML='© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a> · <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noopener">ODbL</a> · Natural Earth boundary';
}
function mapBase(){
 for(const id of ['land','boundary','graticule','stations'])$(id).replaceChildren();
 $('mapbox').style.background=state.osm?'#c8dfe4':'#e7efed';
 $('sea').setAttribute('fill',state.osm?'#c8dfe4':'#e7efed');
 for(const feature of DATA.geography.features){const sa=feature.properties.name==='Saudi Arabia';node('path',{d:polygonPath(feature.geometry),fill:state.osm?'#f3efe4':sa?'#f4f8f1':'#d8e5df',stroke:sa?'#1d6057':state.osm?'#bdc2b5':'#a4b9b1','stroke-width':sa?1.8:.8,'pointer-events':'none'},$('land'));if(sa)node('path',{d:polygonPath(feature.geometry),fill:'none',stroke:'#1d6057','stroke-width':1.8,'pointer-events':'none'},$('boundary'));}
 offlineBackground();
 if(!state.osm){$('mapStatus').textContent='Offline boundary map';$('attribution').textContent='Natural Earth · display boundary, not a survey boundary';}
 if($('grid').checked){const step=state.zoom>7?1:state.zoom>6?2:5;for(let lon=20;lon<=65;lon+=step){const x=xy(lon,24)[0];if(x<65||x>825)continue;node('path',{d:`M${x} 0V480`,fill:'none',stroke:'#8ea7a0','stroke-width':.7,'stroke-dasharray':'2 5'},$('graticule'));text(x+3,465,lon+'°E',$('graticule'),{'font-size':11});}for(let lat=10;lat<=40;lat+=step){const y=xy(44,lat)[1];if(y<85||y>430)continue;node('path',{d:`M0 ${y}H850`,fill:'none',stroke:'#8ea7a0','stroke-width':.7,'stroke-dasharray':'2 5'},$('graticule'));text(7,y-5,lat+'°N',$('graticule'),{'font-size':11});}}
 for(const s of DATA.stations){const [x,y]=xy(s.lon,s.lat);if(x<-10||x>860||y<-10||y>490)continue;const match=!!(s.segments.length&&s.solution);const e=node('circle',{cx:x,cy:y,r:s.id===state.station?5:3.2,fill:match?'#175d59':'#f9fcfa',stroke:match?'#ffffff':'#92aaa3','stroke-width':.8,class:'dot','data-station':s.id},$('stations'));node('title',{},e).textContent=`${s.id} · ${s.domes} · ${match?'Reference and March solution':'Context only'}`;}
 const mpp=40075016.6856*Math.cos(state.center[1]*Math.PI/180)/(256*2**state.zoom),maxKm=mpp*110/1000,scaleKm=[.1,.2,.5,1,2,5,10,20,50,100,200,500,1000].filter(v=>v<=maxKm).pop()||.1;$('scaleBar').style.width=(scaleKm*1000/mpp/850*$('mapbox').clientWidth)+'px';$('scaleText').textContent=scaleKm+' km at map centre';mapMotion();
}
function mapMotion(){const g=$('mapMotion');g.replaceChildren();const s=station(),[x,y]=xy(s.lon,s.lat),r=result(),v=r?.values,b=rigid(s);node('circle',{cx:x,cy:y,r:8,fill:'none',stroke:'#a36b0a','stroke-width':2},g);if($('vectors').checked)node('line',{x1:x,y1:y,x2:x+b[0],y2:y-b[1],stroke:'#1b668b','stroke-width':1.7,'marker-end':'url(#velocityArrow)'},g);
 if(v&&$('motion').checked){const factor=.5,dx=v[0]*factor,dy=-v[1]*factor;node('line',{x1:x,y1:y,x2:x+dx,y2:y+dy,stroke:'#a36b0a','stroke-width':2},g);node('circle',{cx:x+dx,cy:y+dy,r:4,fill:'#a36b0a',stroke:'white','stroke-width':1.5},g);}
}
function chart(){const svg=$('chart');svg.replaceChildren();const s=station(),r=result(),plot={x:58,y:23,w:515,h:139};if(!r){text(50,90,'No matched reference solution for this station.',svg);return;}const sample=state.view==='supplied'?[[OBS,r.values]]:Array.from({length:361},(_,i)=>{const t=2017+i/24;return[t,result(s,t).values];});if(state.view==='illustrative'&&state.event)sample.push([2025-1e-6,result(s,2025-1e-6).values]);sample.sort((a,b)=>a[0]-b[0]);const vals=sample.flatMap(x=>x[1]);const lo=Math.min(-2,...vals),hi=Math.max(2,...vals),pad=(hi-lo)*.13,y=v=>plot.y+plot.h-(v-lo+pad)/(hi-lo+2*pad)*plot.h,x=t=>plot.x+(t-2017)/15*plot.w;
 text(5,14,'mm',svg,{class:'axis'});for(let i=0;i<=3;i++){const value=lo-pad+(hi-lo+2*pad)*i/3,Y=y(value);node('line',{x1:plot.x,x2:plot.x+plot.w,y1:Y,y2:Y,stroke:'#d2dfda'},svg);text(48,Y+4,Math.round(value),svg,{'text-anchor':'end',class:'axis'});}node('line',{x1:x(2017),x2:x(2017),y1:plot.y,y2:plot.y+plot.h,stroke:'#78968c'},svg);for(const year of [2017,2022,2027,2032])text(x(year),184,year===2017?'2017 / t₀':String(year),svg,{'text-anchor':year===2017?'start':year===2032?'end':'middle',class:'axis'});
 for(let j=0;j<3;j++){if(state.view!=='supplied')node('path',{d:sample.map((a,i)=>(i?'L':'M')+x(a[0])+','+y(a[1][j])).join(''),stroke:colors[j],'stroke-width':2.3,fill:'none','stroke-dasharray':['','7 4','2 4'][j]},svg);const current=r.values[j];const mark=node(j===1?'rect':'circle',j===1?{x:x(state.t)-3.5,y:y(current)-3.5,width:7,height:7,fill:colors[j]}:{cx:x(state.t),cy:y(current),r:j===2?3.5:4.5,fill:colors[j],stroke:'white','stroke-width':1},svg);node('title',{},mark).textContent=`${axes[j]}: ${mm(current)}`;}
 node('line',{x1:x(state.t),x2:x(state.t),y1:plot.y,y2:plot.y+plot.h,stroke:'#224c4a','stroke-dasharray':'2 4',opacity:.5},svg);if(state.view==='illustrative'&&state.event){node('line',{x1:x(2025),x2:x(2025),y1:plot.y,y2:plot.y+plot.h,stroke:'#ae3b35','stroke-dasharray':'4 3'},svg);text(x(2025)+4,20,'Synthetic event',svg,{style:'fill:#ad3e35','font-size':11});}}
const intros={supplied:'Inspect the supplied 11 March 2026 coordinate solution after alignment to KSA-GRF17. Each number opens its source and calculation. One solution epoch does not establish a movement trend.',published:'Explore rigid Arabian Plate motion from the published SANSRS rotation parameters. These are model predictions evaluated at supplied station locations.',illustrative:'Explore how local trends, annual motion and an optional event can change coordinates. The added deformation terms in this view are entirely synthetic.'};
function refresh(full=true){const s=station(),r=result(),sup=state.view==='supplied',ill=state.view==='illustrative';$('viewIntro').textContent=intros[state.view];document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.setAttribute('aria-pressed',b.dataset.view===state.view);});$('badge').textContent=sup?'Supplied solution + published transformation':ill?'Synthetic deformation enabled':'Published rigid-plate prediction';$('badge').classList.toggle('synthetic',ill);
 $('valueTitle').textContent=sup?'Difference from the propagated reference':'Change from reference epoch 2017.0';$('valueContext').textContent=sup?`${s.id} · IGS14 → KSA-GRF17 · ${state.reference==='csv'?'CSV reference as supplied':'SINEX linear reference (extrapolated)'}`:`${s.id} · ${state.frame==='global'?'Global-frame comparison':state.frame==='plate'?'Plate-fixed coordinates':'Fixed reference record'}`;
 ['east','north','up'].forEach((id,i)=>$(id).textContent=r?mm(r.values[i]):'—');$('valueWarning').textContent=sup?'Calculated solution differences; they are not a verified deformation time series. March-solution uncertainty is unavailable.':ill?'Synthetic local rates, seasonal terms and event offsets. Click any value to inspect the individual contributions.':'Rigid rotation only. No local deformation, seasonal term or event is inferred from the Technical Summary.';
 $('chartStatus').textContent=sup?'A single solution is shown as three component points at 11 March 2026. No intervening observations or fitted trend are invented.':'Lines show model predictions; the cursor and map use the same epoch and calculation. Up is ellipsoidal, not orthometric height.';
 $('frameLabel').classList.toggle('hidden',sup);$('referenceLabel').classList.toggle('hidden',!sup);$('eventLabel').classList.toggle('hidden',!ill);$('frame').value=state.frame;$('reference').value=state.reference;$('event').checked=state.event;
 $('modelExplanation').textContent=sup?'KSA(t) = IGS14(t) + rotation correction. Compare this with the reference position plus its supplied velocity × elapsed time.':state.frame==='static'?'The coordinate record stays at 2017.0. This says nothing about whether the ground moves.':state.frame==='plate'?'The rigid plate trend is removed. Local deformation can still exist in a plate-fixed frame.':'Global change = rigid plate prediction + any enabled synthetic local terms.';
 $('epochText').textContent=sup?'Solution epoch · 11 Mar 2026, 12:00 UTC':'Epoch '+state.t.toFixed(3);$('epoch').value=state.t;$('epochNumber').value=state.t.toFixed(3);for(const id of ['epoch','epochNumber','play','reset','speed'])$(id).disabled=sup||((id==='play')&&reduced.matches);$('pause').disabled=sup||!state.playing;$('play').textContent=state.playing?'Playing…':'Play';$('timeNote').textContent=sup?'Epoch is fixed by the CRD header. To explore other dates, select a model view.':`Time axis: Julian years of 365.25 days since 2017-01-01. Playback: 0.25 year/second at 1×.${reduced.matches?' Reduced-motion preference: use the slider; playback is disabled.':''}`;
 const seg=segment(s),loc=`${s.lat.toFixed(5)}° N · ${s.lon.toFixed(5)}° E`,identity=`${s.id} · ${s.domes}`;$('stationDetail').innerHTML=`<p><strong>${esc(identity)}</strong> &nbsp; ${loc}</p><p>${seg?'Reference solution segment '+seg.soln+' · 2017.0 catalogue':'Location from the earlier 209-station workbook; no matching reference in the new archive.'}${s.solution?' · CRD flag: '+esc(s.solution.flag):''}</p><p class="small">Displacement: 0.5 map pixels/mm (exaggerated). Selected rigid velocity: 1 map pixel/(mm/year). These scales stay fixed as the geography is zoomed.</p>`;
 if(full)mapBase();else mapMotion();chart();window.explorerState={...state,values:r?.values,terms:r?.terms,observedEpoch:OBS};}
function setView(view){state.view=view;state.playing=false;if(view==='supplied'){state.t=OBS;state.frame='plate';}if(view==='published')state.frame='global';if(view==='illustrative')state.frame='plate';refresh();}
function options(){const query=$('search').value.trim().toUpperCase(),filtered=DATA.stations.filter(s=>(s.id+' '+s.domes).includes(query));$('station').replaceChildren();for(const s of filtered){const o=document.createElement('option');o.value=s.id;o.textContent=s.id+(s.segments.length?'':' · context');$('station').appendChild(o);}if(filtered.some(s=>s.id===state.station))$('station').value=state.station;else if(filtered.length)selectStation(filtered[0].id);}
function selectStation(id){state.station=id;$('station').value=id;refresh();}
function provenance(axis=null){state.playing=false;refresh(false);const s=station(),r=result(),sup=state.view==='supplied';$('provTitle').textContent=axis===null?'Sources & calculations':axes[axis]+' · where this value comes from';
 let body=`<p><strong>${esc(s.id)} · ${esc(s.domes)}</strong><br>View: ${esc(state.view)} · elapsed time: ${(state.t-2017).toFixed(8)} Julian years from 2017-01-01.</p>`;
 if(!r)body+='<p>No matched reference is available. The interface intentionally leaves coordinate differences blank.</p>';
 else{body+='<div class="tablewrap"><table><thead><tr><th>Contribution</th><th>East (mm)</th><th>North (mm)</th><th>Up (mm)</th></tr></thead><tbody>'+r.terms.map((a,i)=>'<tr><td>'+r.labels[i]+'</td>'+a.map((v,j)=>`<td class="num" ${j===axis?'style="font-weight:700"':''}>${f(v,4)}</td>`).join('')+'</tr>').join('')+'<tr><th>Total</th>'+r.values.map(v=>`<td class="num"><strong>${f(v,4)}</strong></td>`).join('')+'</tr></tbody></table></div>';
 if(sup){const seg=r.r;body+=`<p class="formula">ΔENU = R<sub>ENU</sub> · [X<sub>IGS14</sub>(t) − (ω × X<sub>IGS14</sub>(t))·Δt − (X₀ + V₀·Δt)] × 1000</p><p>Positions X are in metres; velocity V₀ is in metres/year; ω is in radians/year; R converts Earth-centred Cartesian differences to local East, North and Up. The minus sign converts the physical plate rotation into the published ITRF2014-to-KSA-GRF transformation.</p><div class="tablewrap"><table><tr><th>Input (X / Y / Z)</th><th>Values</th></tr><tr><td>March IGS14 solution, m</td><td><code>${s.solution.xyz.map(v=>v.toFixed(5)).join(' / ')}</code></td></tr><tr><td>2017 reference, m</td><td><code>${r.base.map(v=>v.toFixed(6)).join(' / ')}</code></td></tr><tr><td>Reference velocity, m/year</td><td><code>${r.velocity.map(v=>v.toFixed(9)).join(' / ')}</code></td></tr></table></div><p>Reference source: <code>${state.reference==='csv'?'KSA-GRF-2017-GCS.csv':'KSA-GRF-2017-GCS.SNX'}</code>, station ${esc(s.id)}, segment ${seg.soln}. SINEX observation span: ${esc(seg.span.join(' to '))} (YY:day-of-year:seconds).</p>`;
 if(state.reference==='snx')body+=`<p class="notice">Reference-only formal 1σ at this epoch (East / North / Up): ${formalReferenceSigma(seg,state.t).map(v=>v.toFixed(2)+' mm').join(' / ')}. This uses the segment’s full position/velocity covariance. It is not the uncertainty of the difference: March-solution covariance and later physical changes are unavailable.</p>`;
 body+='<p>The CSV is a rounded representation of the SINEX values. Zero stored velocities are retained exactly as supplied; they are not a new finding of zero physical motion. A single coordinate file may contain estimated, constrained or propagated coordinates. This archive does not establish that every entry is an independent daily measurement.</p>';
 }else body+='<p class="formula">X(t) = X(t₀) + V·(t − t₀) + P(t) + D(t)</p><p>X is position; t is the selected epoch; t₀ is 2017.0; V is the applicable velocity; P is the periodic change relative to t₀; D is the optional event offset. In the illustrative view, local rates use a longitude-based teaching function; annual amplitudes are 2 / 1.5 / 4 mm, and the optional step is +25 / −12 / +8 mm in East / North / Up.</p>';
 }
 body+='<p><strong>Published input:</strong> SANSRS Technical Summary v3.0 (October 2024), page 19, Table 2.3: transformation rotation rates Rx = −1.199, Ry = +0.107, Rz = −1.468 milliarcseconds/year. Physical plate rotation uses the opposite signs. This teaching calculation implements the first-order position-vector convention; it is not a complete certified transformation service.</p><p><strong>March input:</strong> <code>F1_260700.CRD</code>, header IGS14, 2026-03-11 12:00:00. The file’s processing timestamp in July is not its coordinate epoch.</p><p><strong>Processing report:</strong> <code>R2S260010.PRC</code> concerns 2026-01-01. Its fit statistics must not be applied to the March file.</p>';$('provBody').innerHTML=body;$('provenance').showModal();}
const stories=[['Reference epoch','SANSRS anchors KSA-GRF17 at 2017.0. The reference record supplies a position and, where included, a velocity. Choosing a frame and an epoch comes before comparing coordinates.'],['Plate motion','A stable station on the Arabian Plate changes global-frame coordinates as the plate rotates. The published rotation model predicts this contribution; it is not a measured local deformation signal.'],['Local deformation','A plate-fixed frame removes rigid plate motion. Real local changes require station observations over time. The illustrative view shows how a trend, annual term and event could contribute.'],['Coordinate delivery','A kinematic service can evaluate a coordinate at an observation epoch. Semi-kinematic delivery can instead reduce it to a fixed reference epoch. The frame, epoch, model version and uncertainty travel with the result.']];
function story(){const a=stories[state.story];$('storyTitle').textContent=(state.story+1)+' / '+a[0];$('storyText').textContent=a[1];$('storyPrev').disabled=state.story===0;$('storyNext').textContent=state.story===3?'Start again':'Next →';}
function compare(){const a=Number($('epochA').value),b=Number($('epochB').value);if(!Number.isFinite(a)||!Number.isFinite(b)||a<2017||a>2032||b<2017||b>2032){$('compareResult').textContent='Enter epochs from 2017 to 2032.';return;}if(state.view==='supplied'){$('compareResult').innerHTML='<p class="notice">The archive supplies only one new coordinate epoch. Choose a model view to compare predicted positions at arbitrary epochs.</p>';return;}const A=result(station(),a).values,B=result(station(),b).values;$('compareResult').innerHTML='<table><tr><th>Component</th><th>Epoch A (mm)</th><th>Epoch B (mm)</th><th>B − A (mm)</th></tr>'+axes.map((axis,i)=>`<tr><td>${axis}</td><td>${f(A[i])}</td><td>${f(B[i])}</td><td>${f(B[i]-A[i])}</td></tr>`).join('')+'</table><p class="small">'+esc(state.view)+' · '+esc(state.frame)+' · model prediction, not an observed time series.</p>';}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function exportCsv(){const s=station(),r=result();if(!r){toast('No matched coordinate comparison for this station.');return;}const rows=[['station','domes','view','coordinate_basis','epoch_julian_year','elapsed_years','component','term','value_mm','provenance']];r.terms.forEach((v,k)=>v.forEach((x,j)=>rows.push([s.id,s.domes,state.view,state.view==='supplied'?'KSA-GRF17 local ENU':state.frame,state.t,state.t-2017,axes[j],r.labels[k],x,state.view==='supplied'?'F1_260700.CRD; '+(state.reference==='csv'?'KSA-GRF-2017-GCS.csv':'KSA-GRF-2017-GCS.SNX')+'; SANSRS v3 Table 2.3':k===0?'SANSRS v3 Table 2.3':'Synthetic teaching term'])));r.values.forEach((v,j)=>rows.push([s.id,s.domes,state.view,state.frame,state.t,state.t-2017,axes[j],'Total',v,'Calculated; not operational']));download(`KSA_${s.id}_${state.view}_calculation.csv`,'\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');}
function exportSvg(){const s=station(),r=result(),clone=$('map').cloneNode(true);clone.querySelectorAll('path').forEach(e=>{if(e.getAttribute('fill-opacity')==='0.1')e.setAttribute('fill-opacity','1');});clone.setAttribute('x','30');clone.setAttribute('y','145');clone.setAttribute('width','850');clone.setAttribute('height','480');clone.querySelectorAll('text').forEach((e,i)=>e.style.fontSize=getComputedStyle($('map').querySelectorAll('text')[i]).fontSize);const chartClone=$('chart').cloneNode(true);chartClone.setAttribute('x','910');chartClone.setAttribute('y','350');chartClone.setAttribute('width','600');chartClone.setAttribute('height','210');chartClone.querySelectorAll('text').forEach((e,i)=>e.style.fontSize=getComputedStyle($('chart').querySelectorAll('text')[i]).fontSize);const serialized=new XMLSerializer().serializeToString(clone),serializedChart=new XMLSerializer().serializeToString(chartClone);const lines=[['Coordinate source',state.view==='supplied'?'Supplied March solution + published frame rotation':state.view==='published'?'Published rigid-plate prediction':'Synthetic local deformation enabled'],['Epoch',state.view==='supplied'?'2026-03-11 12:00 UTC':state.t.toFixed(3)],['Basis',state.view==='supplied'?'KSA-GRF17; '+state.reference+' reference':state.frame]];
 const svg=`<svg xmlns="${NS}" width="1600" height="900" viewBox="0 0 1600 900"><title>KSA coordinate explorer snapshot</title><desc>Static snapshot; bundled regional OpenStreetMap vectors retained. ${esc(intros[state.view])}</desc><rect width="1600" height="900" fill="#f5f8f7"/><style>text{font-family:Segoe UI,Arial;fill:#173e40;font-size:18px}.axis{font-size:12px}</style><text x="30" y="55" style="font-size:30px;font-weight:600">Saudi Arabia · ${esc(s.id)} · ${esc(s.domes)}</text><text x="30" y="92">${esc(intros[state.view].split('. ')[0])}.</text>${serialized}${serializedChart}${axes.map((a,i)=>`<text x="${910+i*205}" y="195">${a}</text><text x="${910+i*205}" y="240" style="font-size:28px">${r?mm(r.values[i]):'Unavailable'}</text>`).join('')}${lines.map((a,i)=>`<text x="30" y="${670+i*30}">${esc(a[0]+': '+a[1])}</text>`).join('')}<text x="30" y="778">Map: © OpenStreetMap contributors / ODbL; Natural Earth · displacement 0.5 map px/mm · rigid velocity 1 map px/(mm/year), exaggerated</text><text x="30" y="820">Author: Abdulwasa Salawu B.Eng, MSc, MBA, DevOps Bootcamp Student.</text><text x="30" y="850">Technical Advisor UNDP-GEOSA · Demonstration only — not for survey or operational use</text><text x="30" y="881">SANSRS Technical Summary v3.0, Table 2.3 · coordinates_for_sites_for_report.zip · 16 September 2026</text></svg>`;download(`KSA_${s.id}_${state.view}_snapshot.svg`,svg,'image/svg+xml');toast('SVG snapshot exported with offline geography and source labels.');}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('search').addEventListener('input',options);$('station').onchange=()=>selectStation($('station').value);$('frame').onchange=()=>{state.frame=$('frame').value;refresh(false);};$('reference').onchange=()=>{state.reference=$('reference').value;refresh(false);};$('event').onchange=()=>{state.event=$('event').checked;refresh(false);};['grid','vectors','motion'].forEach(id=>$(id).onchange=()=>refresh());
$('epoch').oninput=()=>{state.t=Number($('epoch').value);state.playing=false;refresh(false);};$('epochNumber').onchange=()=>{const t=Number($('epochNumber').value);if(Number.isFinite(t))state.t=Math.max(2017,Math.min(2032,t));state.playing=false;refresh(false);};$('play').onclick=()=>{if(reduced.matches||state.view==='supplied')return;if(state.t>=2032)state.t=2017;state.playing=true;last=0;refresh(false);};$('pause').onclick=()=>{state.playing=false;refresh(false);};$('reset').onclick=()=>{state.playing=false;state.t=2017;refresh(false);};
$('fit').onclick=()=>{state.center=[44,24.5];state.zoom=5;mapBase();};$('focus').onclick=()=>{state.center=[station().lon,station().lat];state.zoom=9;mapBase();};function zoom(delta){state.zoom=Math.max(4,Math.min(15,state.zoom+delta));mapBase();}$('zoomIn').onclick=()=>zoom(1);$('zoomOut').onclick=()=>zoom(-1);
$('osm').onchange=()=>{state.osm=$('osm').checked;mapBase();};
let drag=null,mapDragged=false;const mapPoint=e=>new DOMPoint(e.clientX,e.clientY).matrixTransform($('map').getScreenCTM().inverse());$('map').addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={point:mapPoint(e),center:world(...state.center)};mapDragged=false;$('map').setPointerCapture(e.pointerId);});$('map').addEventListener('pointermove',e=>{if(!drag)return;const pt=mapPoint(e),dx=pt.x-drag.point.x,dy=pt.y-drag.point.y;if(Math.abs(dx)+Math.abs(dy)<4)return;mapDragged=true;const size=256*2**state.zoom;state.center=lonlat(drag.center[0]-dx/size,drag.center[1]-dy/size);state.center[0]=Math.max(20,Math.min(65,state.center[0]));state.center[1]=Math.max(10,Math.min(40,state.center[1]));mapBase();});$('map').addEventListener('pointerup',e=>{if(drag&&!mapDragged){const pt=mapPoint(e);let closest=null,d=12;for(const s of DATA.stations){const [x,y]=xy(s.lon,s.lat),dist=Math.hypot(pt.x-x,pt.y-y);if(dist<d){closest=s;d=dist;}}if(closest)selectStation(closest.id);}drag=null;});$('map').addEventListener('pointercancel',()=>drag=null);$('map').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?-.25:.25);},{passive:false});$('map').addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1);}else if(e.key==='-'){e.preventDefault();zoom(-1);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const c=world(...state.center),step=40/(256*2**state.zoom);state.center=lonlat(c[0]+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0),c[1]+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0));mapBase();}});
$('sourceButton').onclick=()=>provenance();document.querySelectorAll('[data-axis]').forEach(b=>b.onclick=()=>provenance(Number(b.dataset.axis)));$('closeProvenance').onclick=()=>$('provenance').close();$('compareButton').onclick=()=>{$('epochB').value=state.t.toFixed(3);$('compareNote').textContent=state.view==='supplied'?'Only one new coordinate epoch is available in the archive.':'Compare model predictions for the selected station and coordinate view.';$('compare').showModal();compare();};$('closeCompare').onclick=()=>$('compare').close();$('calculateCompare').onclick=compare;$('csvExport').onclick=exportCsv;$('svgExport').onclick=exportSvg;$('print').onclick=()=>print();$('storyPrev').onclick=()=>{state.story=Math.max(0,state.story-1);story();};$('storyNext').onclick=()=>{state.story=(state.story+1)%4;story();};
$('inventory').innerHTML=`<div class="data-grid"><div><strong>${DATA.summary.referenceStations}</strong><span>Matched reference stations</span></div><div><strong>${DATA.summary.csvRecords}</strong><span>Reference solution segments</span></div><div><strong>1</strong><span>New coordinate epoch</span></div></div><div class="tablewrap"><table><tr><th>File</th><th>What it supplies</th></tr><tr><td><code>F1_260700.CRD</code></td><td>485 coordinate entries; IGS14, 11 March 2026.</td></tr><tr><td><code>KSA-GRF-2017-GCS.csv</code></td><td>2017.0 reference positions and velocities.</td></tr><tr><td><code>KSA-GRF-2017-GCS.SNX</code></td><td>864 estimates; position/velocity covariance and observation spans.</td></tr><tr><td><code>R2S260010.PRC</code></td><td>Processing diagnostics for 1 January 2026.</td></tr></table></div><p class="small">${DATA.summary.networkStations} unique station IDs are shown across the old workbook and new catalogue. ${DATA.summary.matchedReferenceSolution} have matched catalogue and March solution entries. Station ID and DOMES must both agree.</p>`;
$('roundingNote').textContent=`CSV/SINEX coordinate agreement: largest component rounding difference ${DATA.summary.maxCsvSnxPositionDifferenceMm.toFixed(3)} mm. Zero/nonzero velocity mismatches: ${DATA.summary.csvZeroSnxNonzeroSegments}. Solution segments are selected using the CSV date intervals; SINEX spans describe contributing observations, not future validity.`;
$('osm').checked=true;options();story();refresh();new ResizeObserver(()=>mapBase()).observe($('mapbox'));
reduced.addEventListener('change',()=>{if(reduced.matches)state.playing=false;refresh(false);});let last=0;function tick(now){if(state.playing&&last){state.t=Math.min(2032,state.t+Math.min(now-last,100)/1000*.25*Number($('speed').value));if(state.t>=2032)state.playing=false;refresh(false);}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);
